CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE timelog (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    clock_in TIMESTAMP NOT NULL,
    clock_out TIMESTAMP NOT NULL
);